name: Find and Run SignTool Versions

on:
  workflow_dispatch:

jobs:
  find-and-run-signtool-versions:
    runs-on: windows-latest

    steps:
      - name: Find and Run SignTool Versions
        id: find-and-run-signtool-versions
        run: |
          # Find all versions of signtool.exe in the folder, excluding 'arm' architecture
          $signtool_paths = Get-ChildItem "C:\Program Files (x86)\Windows Kits\10\bin" -Recurse -Filter signtool.exe | Where-Object { $_.FullName -notmatch 'arm' } | Select-Object -ExpandProperty FullName

          # Loop through each version and run signtool /?
          foreach ($signtool_path in $signtool_paths) {
            echo "Running signtool /? for $signtool_path"
            & $signtool_path sign /?
          }
