name: List Program Files Directory

on:
  workflow_dispatch:

jobs:
  list-program-files:
    runs-on: windows-latest

    steps:
      - name: List Program Files Directory
        id: list-program-files
        run: |
          Get-ChildItem "C:\Program Files" -Recurse | Where-Object {$_.FullName -like "*signtool*" -or $_.FullName -like "*Signtool*"} | Select-Object FullName
